name: Schedule Test 3 with push and ''

on:
  workflow_dispatch:

  push:

  schedule:
    - cron: '*/10 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello Schedule with push"