# 動作確認用
name: GitHub Actions cron Test

# 手動実行
on:
  workflow_dispatch:

  # schedule:
  # - cron: "*/5 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python
        run: python src/main.py