# 動作確認用
name: GitHub Actions Test

# 手動実行
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run test command
        run: echo "GitHub Actions works!"