# 動作確認用
name: cron Test


on:
  workflow_dispatch:

  # push :

  # schedule:
  #   - cron: '0,30 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python
        run: python main.py